meshery-extensions/meshery-nsm

Makefile

Signed-off-by: leecalcote <leecalcote@gmail.com>

init makefile

---

.github/workflows/ci.yml
CONTRIBUTING.md

Signed-off-by: subhamkrai <subhamkumarrai03@gmail.com>

#20 created contributing.md file

---

README.md

Fixed badges and logo hyperlinks.
Fix issue #30

Fix badges hyperlink

---

README.md
nsm/nsm.go

Signed-off-by: Harshini-M <hm@luminanetworks.com>

Update Meshery Logo in README.md

---

nsm/nsm.go
nsm/supported_ops.go

Updating Sample application name from VPN ICMP to VPP-ICMP
Signed-off-by: Harshini-M <hm@luminanetworks.com>

Updated Application Name to VPP-ICMP

---

.github/ISSUE_TEMPLATE/documentation.md
README.md

Signed-off-by: ashiscs <ashissingh640@gmail.com>

added documentation.md

---

README.md

Signed-off-by: ashiscs <ashissingh640@gmail.com>

added (CII+dynamic slack)badge

---

.github/workflows/ci.yml
README.md

fixes #47 
Signed-off-by: ashiscs <ashissingh640@gmail.com>

enabled static and error checks

---

nsm/client.go
nsm/helpers.go
nsm/install_nsm.go
nsm/maintainers.md
nsm/nsm-cnfs.go
nsm/nsm.go
nsm/supported_ops.go
nsm/yaml.go

Signed-off-by: ashiscs <ashissingh640@gmail.com>

fixes static and error check

---

go.mod
go.sum
nsm/nsm.go
pkg/ioutil/io_util.go
pkg/ioutil/io_util_test.go

Signed-off-by: Aisuko <urakiny@gmail.com>
The PR includes the feature of fixed the error check and can be merged before we merge the PR type of dependencies

Fixed the err check

---

nsm/nsm.go
pkg/ioutil/io_util.go
pkg/ioutil/io_util_test.go

Signed-off-by: Aisuko <urakiny@gmail.com>

Fix  the static check issues

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Signed-off-by: leecalcote <leecalcote@gmail.com>

adding workflows

---

.github/ISSUE_TEMPLATE/documentation.md
.github/PULL_REQUEST_TEMPLATE.md
.github/config.yml

Signed-off-by: Ayushman Mishra <ayushvidushi01@gmail.com>

Changing layer5 link to meshery link

---

README.md

Changing layer5 link to meshery link
Signed-off-by: Aaroosh Agarwal <aaroosh.2012@gmail.com>
fixed the slack icon in the readme
This PR fixes #102 

Fixed Slack icon in readme

---

README.md

Update the link for help-wanted label
This PR fixes #

Update the link for help-wanted label

---

README.md

Signed-off-by: Mritunjay <msengar121@gmail.com>
This PR fixes #115 

aligned discuss in readme.md 

---

internal/config/config.go

Signed-off-by: Rudraksh Pareek <rudrakshpareek3601@gmail.com>
This PR fixes #

[chore] make NSM install operation name compliant with SMP protos

---

.github/workflows/build-and-release.yml

Signed-off-by: Michael Gfeller <mgfeller@mgfeller.net>
Added build-arg GIT_COMMITSHA and VERSION to docker build for edge and stable.
This PR fixes #124 

[Bug] Fixed incorporating adapter version # at buildtime

---

Dockerfile

Signed-off-by: Aadhitya A <aadhitya864@gmail.com>
This PR is related to meshery/meshery#4642
WIP and subject to tests

[WIP] Fix CVE issues by upgrading tags

---

.github/workflows/newcomers-alert.yml

Signed-off-by: Srinivas karnati <karnatisrinivasulareddy@gmail.com>
This PR fixes #

minor change in workflow

---

Dockerfile

Signed-off-by: Ruturaj Mohite <53974118+gr455@users.noreply.github.com>
This PR fixes #

NSM: Remove arch hardcode and kubeopenapi-jsonschema
